version: '3.7'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: frost75/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: frost75/foodgram_frontend
    command: cp -r /app/result_build/. /static/
    volumes:
      - static:/static/
    depends_on:
      - backend

  gateway:
    image: frost75/foodgram_gateway
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - frontend:/usr/share/nginx/html/
    depends_on:
      - frontend
      - backend