version: '3.7'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: frost75/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: frost75/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    image: frost75/foodgram_gateway
    ports:
      - 8000:8000
    command: cp -r /var/docs/. /static/
    volumes:
      - static:/usr/share/nginx/html
      - media:/var/html/media
    depends_on:
      - frontend
      - backend