# Generated by Django 4.2.2 on 2023-06-28 10:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shoppingcart',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
