# Generated by Django 4.2.2 on 2023-07-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shoppingcart',
            managers=[
            ],
        ),
    ]
